### ISSUE TITLE
Vault Plugin global level

### ISSUE THREAD

**Issue by palvarado38** [jenkinsci/hashicorp-vault-plugin#102]
I have Jenkins running on macOS for testing and on a windows server, I'm having an issue getting the hashicorp plugin on the windows server to provide the vault options under x.x.x.x/configure/Vault Plugin when I go to add the token I do not see the vault options compared to the doc and macOS device.  Am I missing a setting? 

mac device:
<img width="1203" alt="Screen Shot 2020-05-26 at 9 40 57 PM" src="https://user-images.githubusercontent.com/65562406/82971988-9e210c00-9f99-11ea-8087-046b5267c359.png">

windows device:
<img width="1146" alt="Screen Shot 2020-05-26 at 9 42 22 PM" src="https://user-images.githubusercontent.com/65562406/82972086-d1639b00-9f99-11ea-9881-20ed1d2d43bf.png">

**Comment by jetersen** [comment]
Seems on your windows machine the plugin is not installed, only logical explanation as to why it is missing.

**Comment by palvarado38** [comment]
<img width="1476" alt="Screen Shot 2020-08-31 at 7 52 55 PM" src="https://user-images.githubusercontent.com/65562406/91782782-ba010300-ebc3-11ea-8c9a-e548ac02a63a.png">

**Comment by jetersen** [comment]
I cannot reproduce the issue.
