### ISSUE TITLE
support for nested json keys

### ISSUE THREAD

**Issue by pyrocks** [jenkinsci/hashicorp-vault-plugin#103]
Hi,

I have a json secret defined under 'secrets/mysecret'
The json looks like
```
{
    "mykey1": {
        "mykey2": "password"
    }
}
```

I tried to configure a withVault closure to get "mykey2"'s value but wasn't able to.
I was only able to get the root key "mykey1" - so this works:
```
def secrets = [
        [path: 'secret/mysecret', engineVersion: 2, secretValues: [
            [envVar: 'vaultpass', vaultKey: 'mykey1']
        ]]
    ]
```
But then I have to parse the Json to get the actual key I need.
If I replace vaultKey's value to  `mykey1.mykey2` it doesn't work.
I also tried json path syntax like `$.mykey1.mykey2` and the likes.

The reason I have a nested json is due to different environments, but if this isn't supported I might have to switch to standard key-value pairs.

Thanks.

**Comment by jetersen** [comment]
What you have as secrets is beyond what the plugin is responsible for parsing.
The plugins job is only to fetch secrets.

it is up to you the consumer to properly consume your secrets data.

**Comment by jetersen** [comment]
You can use the pipeline utility steps plugins.
Which offers reading JSON: https://github.com/jenkinsci/pipeline-utility-steps-plugin/blob/master/docs/STEPS.md

**Comment by pyrocks** [comment]
Thanks for the prompt reply.
My problem with this is that if I parse the json response,  the secret is not longer masked when being used as a partial string to the original fetched key (only the fetched key is masked).

While I can work around it by adding a password masking plugin step - it's not very convenient.

It would have been nice if it supported json paths...
If it won't be supported I will have to unnest my json or create multiple secrets for the different envs.

**Comment by jetersen** [comment]
I suggest creating a script that can parse the secret json without logging it.

bash script using jq will do the job.

**Comment by pyrocks** [comment]
Thanks. Still would have been nice if it was supported.
Closing as I understand there is no intention of supporting it as part of the plugin.
