### ISSUE TITLE
[QUESTION] Different Vaults in one job

### ISSUE THREAD

**Issue by tsologub** [jenkinsci/hashicorp-vault-plugin#116]
**Usecase:** a Jenkins job requires to read secrets from different namespaces. For each Vault namespace, I setup Jenkins AppRole. The generated `role_id` and `secret_id` I store in Jenkins Credentials store. But I can only select/use one Vault credential per job. (the Vault Credential dropdown).

Is there a way/workaround to use multiple Vault Credentials per one Jenkins job?

**Comment by jetersen** [comment]
Switch to pipeline if you need such a complex job? 🤔

**Comment by tsologub** [comment]
Not complex. One job used by 2 teams. Each team has it's own namespace. Some part of credentials comes from Team A namespace, another part from Team B namespace.

**Comment by jetersen** [comment]
use pipeline it is more flexible. What your asking for cannot be supported in freestyle without major rework of the plugin.
