### ISSUE TITLE
Accessing vault secret with full path

### ISSUE THREAD

**Issue by gunhu** [jenkinsci/hashicorp-vault-plugin#117]
Hi,

The documentation is still up-to-date about this feature?

With hashicorp vault plugin version 2.5.0 and Jenkins 2.235.3 it seems to not be working anymore.

If I'm using this form:

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              description: "Secret using only secret key name"
              id: "secretUsingKey"
              scope: GLOBAL
              token: "${secretKey1}"

No issues so far but with the second one:

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              description: "Secret using full path"
              id: "secretUsingKey"
              scope: GLOBAL
              token: "${secret/jenkins/passwords/secretKey1}"

To no avail so far, is anybody is using the second form and can help me ? secret and key are valid.

If more information is needed feel free to ask me.

Regards,

**Comment by jetersen** [comment]
Full path is only supported from [`v3.4.0`](https://github.com/jenkinsci/hashicorp-vault-plugin/releases/tag/hashicorp-vault-plugin-3.4.0)
