### ISSUE TITLE
[QUESTION] Is withVault supported in downstream jobs (triggered with build step)?

### ISSUE THREAD

**Issue by imann24** [jenkinsci/hashicorp-vault-plugin#118]
Hi, I was curious if it's supported to use `withVault` inside a job triggered with the `build` command/step ( https://www.jenkins.io/doc/pipeline/steps/pipeline-build-step ). From what I've observed, the plugin does not seem able to retrieve secrets in a job triggered within another Jenkins job.

**Comment by jetersen** [comment]
it's a separate build, so the answer would always be no.

**Comment by imann24** [comment]
In case my phrasing was unclear, the withVault wrapper is part of the pipeline for the downstream job. It is able to retrieve the secrets when the job is run manually, but not when that job is triggered by another.
