### ISSUE TITLE
Store the token in a field instead of getting a new one each time in VaultAppRoleCredential

### ISSUE THREAD

**Issue by starchen** [jenkinsci/hashicorp-vault-plugin#133]
Hi,

in the VaultAppRoleCredential, the getToken() method retrieves a new token each time it is called, by consuming roleId and secretId. (https://github.com/jenkinsci/hashicorp-vault-plugin/blob/5a1eedadbde028ac133764c83bbd2c7af5098b00/src/main/java/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredential.java#L51)
The problem is when we use a single-use and short-lived SecretID, we have to regenerate a new SecretId each time we want to access Vault (eg: each time we call withVault() with the same VaultAppRoleCredential in jenkins pipeline, we have to create a new VaultAppRoleCredential before).
Is there any way to store the token somewhere in the VaultAppRoleCredential once it is populated so that the token can be reused, or is the current fashion to retrieve an auth token, the correct and only behavior we should have ?

Thanks

**Comment by dineshba** [comment]
@ash1425 can we close this issue ?

**Comment by ash1425** [comment]
Tested locally, latest version is not generating tokens for each retrieval and reusing same token until expiry. Good to close.
@starchen FYI.

**Comment by dineshba** [comment]
Thanks @ash1425
