### ISSUE TITLE
value credentials not found - using namespaces ?

### ISSUE THREAD

**Issue by lucatoldo** [jenkinsci/hashicorp-vault-plugin#137]
Dear all,
I am keep getting  com.datapipe.jenkins.vault.exception.VaultPluginException: Vault credentials not found for 'mykey'
Could this be a namespace problem ?
if commandline I query without having set the namespace I also get an error (403).
I have seen that the plugin in principle support namespaces, however I could not find how to specify that.
Thankyou

**Comment by lucatoldo** [comment]
Thankyou, according to the sysadmin we are not using a subfolder, the pluginis set as global jenkins configuration

**Comment by lucatoldo** [comment]
Still it does not work

**Comment by jetersen** [comment]
Without more information I cannot assist.

Are you using Pipeline jobs or Freestyle jobs?

What does your config look like?
What does script look like?

**Comment by lucatoldo** [comment]
Thankyou for your followup.
I am using a "Scripted pipeline" (usig the nomenclature in 

node () {   
  def secrets = [
    [ path: 'kv/env', 
         secretValues: [
           [vaultKey: 'test']
         ]
     ]
   ] 
  def configuration = [
    $class: 'VaultConfiguration', 
    vaultUrl: 'https://myvault.myorg.mycom', 
    vaultNamespace:  'my/namespace', 
    vaultCredentialId: 'CR_VAULT_APPROLE'
  ]      
  wrap([$class: 'VaultBuildWrapper', configuration: configuration, vaultSecrets: secrets]) {
   sh 'echo $test' 
  }
}

**Comment by jetersen** [comment]
Are you using vault engine v1 or v2? FYI the plugin will default to v2.

**Comment by jetersen** [comment]
Also see: https://github.com/jenkinsci/hashicorp-vault-plugin/issues/112#issuecomment-679699388

**Comment by lucatoldo** [comment]
Hi Joseph, I am using v2

**Comment by lucatoldo** [comment]
yes I did check #112  but unfortunately I got a different issue. I think the problem is related with namespace handling

**Comment by lucatoldo** [comment]
as you can see, even though I am using the undocumented 

vaultNamespace:"my/namespace"

still it does not work.

commandline fails if I do not specify the namespace and therefore I assume the problem is at this level.

**Comment by jetersen** [comment]
I don't have a vault instance running with namespaces so it is hard for me to know.
Only thing I can suggest is to spin up intellij idea and run `hpi:run` task from maven and attach the debugger.

**Comment by lucatoldo** [comment]
thankyou, I have also opened a ticket to the hashicorp team.

**Comment by lucatoldo** [comment]
@cronik could you please get in touch ?

**Comment by jetersen** [comment]
hashicorp has no affiliation to this plugin.

**Comment by u773357** [comment]
I got same issue - ault credentials not found for - using namespace.
