### ISSUE TITLE
unit tests deliver "cannot listen to UDP port ..." is this ok ?

### ISSUE THREAD

**Issue by lucatoldo** [jenkinsci/hashicorp-vault-plugin#140]
0.015 [id=191]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:53647/jenkins/
 0.035 [id=204]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
 0.037 [id=218]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
 0.232 [id=207]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
 0.234 [id=205]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
 0.235 [id=206]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
 0.303 [id=212]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
 0.308 [id=210]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
 0.311 [id=232]	INFO	hudson.UDPBroadcastThread#run: Cannot listen to UDP port 33,848, skipping: java.net.SocketException: Can't assign requested address (local port 33848 to address 0:0:0:0:0:0:0:0, remote host unknown)
 0.482 [id=220]	INFO	hudson.model.Run#execute: test #1 main build action completed: SUCCESS
 0.492 [id=191]	INFO	jenkins.model.Jenkins#cleanUp: Stopping Jenkins
 80.889 [id=191]	INFO	jenkins.model.Jenkins#cleanUp: Jenkins stopped

**Comment by TobiX** [comment]
Since that feature was removed from Jenkins 2.220, that is probably fine. (See https://jenkins.io/redirect/udp-broadcast)

**Comment by lucatoldo** [comment]
Thankyou @TobiX you were right.
Change to higher version removed the UDP errors.
Unfortunately however many others show up, therefore this item can be closed, and I just opened up a new issue with the specifics of the new errors. #141
