### ISSUE TITLE
Access denied to Vault Secrets at 'path'

### ISSUE THREAD

**Issue by sunnypatel2141** [jenkinsci/hashicorp-vault-plugin#144]
Hi

Our team has been using Vault Engine Version 1 so far where the path was `/generic/project/replication` and that worked fine with Jenkins plugin `withVault`.

However, we recently enabled Version 2 for our project, so we have access to `/project/replication`. 

```
vault kv put project/replication/test key=value
```

```
vault kv get project/replication/test 

key=value
```

The above works fine with a role_id and secret_id. But when I use the same credentials for Jenkins plugin I get `Access denied to Vault Secrets at 'project/replication/test'`

Here's the withVault method:
```
withVault(
  configuration: [timeout: 60, vaultCredentialId: 'vault-test-approle',
  vaultUrl: '<ur>',
  engineVersion: 2], 
  vaultSecrets: [[path: 'project/replication/test',
  secretValues: [[vaultKey: 'apikey']]]])
```

Any idea ? Is Jenkins not supposed with work with Vault Version 2 ?

Thanks.

**Comment by jetersen** [comment]
Depends on the version of the plugin you have installed.

**Comment by sunnypatel2141** [comment]
I see the following in Jenkins:

1) **HashiCorp Vault** - Jenkins plugin to populate environment variables from secrets stored in HashiCorp's Vault - **3.5.0** 
2) **Hashicorp Vault Pipeline Plugin** - Enables pulling of vault values as a pipeline step - **1.3**

**Comment by sunnypatel2141** [comment]
I updated HashiCorp Vault to 3.6.1 but no help.

Is the problem because I created the secret with `vault kv put` and it can be retrieved with `vault kv get`. 

If I use `vault read` to read the secret I get
```
Error reading project ...: Error making API request.

URL: GET ...
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

@jetersen Is your plugin using `read` API to get the secret in V2 ?

**Comment by sunnypatel2141** [comment]
@jetersen Is this an enhancement request ? Do you have access to Vault version 2 where you can test this ?

Thanks.

**Comment by jetersen** [comment]
To my knowledge, the plugin have support for v2

**Comment by sunnypatel2141** [comment]
This is very silly but I had to move half of the secret path to prefixPath and then it worked. Based on https://github.com/jenkinsci/hashicorp-vault-plugin/issues/112

**Comment by jetersen** [comment]
that's namespacing for you. 

The underlying issue is the way the java library is implemented.
