### ISSUE TITLE
 [Question] Disabble output Retrieving secret

### ISSUE THREAD

**Issue by mBouamama** [jenkinsci/hashicorp-vault-plugin#154]
hi,
First, Amazing job thanks for that.
I have a question when i check output on console i see that:
```
Retrieving secret: secret/my_secret_repo/my_secret
Retrieving secret: secret/my_secret_repo/my_secret2
Retrieving secret: secret/my_secret_repo/my_secret3
```
Can I disable output?
Regards.

**Comment by jetersen** [comment]
In jenkins you can set the log level for vault hashicorp plugin to something higher like warning.

**Comment by mBouamama** [comment]
hi,
Thanks for your help but i didn't find the good log's name for this ouput(i try logs of log).Can you help me?
And i prefere to precise this output is printed when on console output of my job.So when i go to jenkins logs i didn't see this output.

**on console Job(view/TEST/job/TEST-WITH-VAULT/17/console)**:
```
Retrieving secret: secret/my_secret_repo/my_secret
Retrieving secret: secret/my_secret_repo/my_secret2
Retrieving secret: secret/my_secret_repo/my_secret3
```

**Jenkins Log(/log/all)**:
```
Jan 29, 2021 2:58:45 PM INFO com.bettercloud.vault.Vault 
The NameSpace MY_NAMESPACE  has been bound to this Vault instance. Please keep this in mind when running operations.
Jan 29, 2021 2:58:45 PM INFO com.bettercloud.vault.Vault 
The NameSpace MY_NAMESPACE has been bound to this Vault instance. Please keep this in mind when running operations.
Jan 29, 2021 2:58:46 PM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
TEST-WITH-VAULT #17 completed: SUCCESS
```
