### ISSUE TITLE
 Support JCasC SecretSource credentials from a credentials ID

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/hashicorp-vault-plugin#170]
### Feature Request

VaultSecretSource could get its AppRole credentials from a pre-existing credentials ID.  This is desirable in a long running Jenkins instance where avoiding sensitive information in environment variables is desirable.

**Comment by jetersen** [comment]
That wouldn't work for those having JCasC configure credentials 🤔

**Comment by samrocketman** [comment]
The idea being you create the credential before running JCasC.  e.g. in AWS you can use an init groovy hook to get secret zero from AWS Secret Manager and create the initial credential; then reload JCasC config.  All this to avoid hard coding a plan text secret in config (I'm referring to AppRole ID and Secret).

**Comment by samrocketman** [comment]
Closing in favor of #169
