### ISSUE TITLE
Vault credentials not found

### ISSUE THREAD

**Issue by Vincent1984** [jenkinsci/hashicorp-vault-plugin#209]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  Jenkins: 2.303.3
OS: Linux - 3.10.0-1160.45.1.el7.x86_64
---
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
authorize-project:1.4.0
blueocean:1.25.2
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.2
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.25.2
blueocean-git-pipeline:1.25.2
blueocean-github-pipeline:1.25.2
blueocean-i18n:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.25.2
blueocean-pipeline-editor:1.25.2
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-3
bouncycastle-api:2.25
branch-api:2.7.0
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:731.v1f980b7eba32
cloudbees-folder:6.16
command-launcher:1.6
config-file-provider:3.8.2
convert-to-pipeline:1.0
credentials:2.6.1
credentials-binding:1.27
display-url-api:2.3.5
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-1
favorite:2.3.3
font-awesome-api:5.15.4-3
git:4.10.0
git-client:3.10.0
git-server:1.10
github:1.34.1
github-api:1.133
github-branch-source:2.11.3
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
hashicorp-vault-pipeline:1.3
hashicorp-vault-plugin:336.v182c0fbaaeb7
htmlpublisher:1.28
jackson2-api:2.13.0-230.v59243c64b0a5
jacoco:3.3.0
javadoc:1.6
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.2
jjwt-api:0.11.2-9.c8b45b8bb173
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
ldap:2.7
localization-support:1.1
localization-zh-cn:1.0.24
lockable-resources:2.12
mailer:1.34
mapdb-api:1.0.9.0
matrix-auth:2.6.8
matrix-project:1.19
maven-plugin:3.15.1
momentjs:1.1.1
nodejs:1.4.2
okhttp-api:4.9.2-20211102
pipeline-build-step:2.15
pipeline-graph-analysis:1.12
pipeline-input-step:2.12
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.19
plain-credentials:1.7
plugin-util-api:2.5.1
popper-api:1.16.1-2
popper2-api:2.10.2-1
pubsub-light:1.16
scm-api:2.6.5
script-security:1.78
snakeyaml-api:1.29.1
sonar:2.14
sse-gateway:1.24
ssh-credentials:1.19
sshd:3.1.0
structs:1.24
subversion:2.15.1
thinBackup:1.10
timestamper:1.14
token-macro:267.vcdaea6462991
trilead-api:1.0.13
variant:1.4
workflow-aggregator:2.6
workflow-api:2.47
workflow-basic-steps:2.24
workflow-cps:2633.v6baeedc13805
workflow-cps-global-lib:548.v9085a486966a
workflow-durable-task-step:1101.vf832bc1ac745
workflow-job:2.42
workflow-multibranch:2.26
workflow-scm-step:2.13
workflow-step-api:2.24
workflow-support:3.8

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

  def secrets = [
        [path: 'secrets/kv/hello', engineVersion: 2, secretValues: [
            [envVar: 'testing', vaultKey: 'target']]]
    ]

    // optional configuration, if you do not provide this the next higher configuration
    // (e.g. folder or global) will be used
    def configuration = [vaultUrl: 'http://vault.liando.cn:8200',
                         vaultCredentialId: 'vault-root-token',
                         engineVersion: 1]
    // inside this block your credentials will be available as env variables
    withVault([configuration: configuration, vaultSecrets: secrets]) {
        sh 'echo $testing'
        sh 'echo $testing_again'
        sh 'echo $another_test'
    }

when I  use root token for the credentials  it shows 
20:30:50  [Pipeline] End of Pipeline
20:30:50  com.datapipe.jenkins.vault.exception.VaultPluginException: Vault credentials not found for 'secrets/kv/hello'
20:30:50  	at com.datapipe.jenkins.vault.VaultAccessor.responseHasErrors(VaultAccessor.java:235)
20:30:50  	at com.datapipe.jenkins.vault.VaultAccessor.retrieveVaultSecrets(VaultAccessor.java:170)
20:30:50  	at com.datapipe.jenkins.vault.VaultBindingStep$Execution.doStart(VaultBindingStep.java:115)
20:30:50  	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
20:30:50  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:30:50  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:30:50  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20:30:50  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20:30:50  	at java.lang.Thread.run(Thread.java:748)
20:30:50  Finished: FAILURE

  def secrets = [
        [path: 'secrets/kv/hello', engineVersion: 2, secretValues: [
            [envVar: 'testing', vaultKey: 'target']]]
    ]

    // optional configuration, if you do not provide this the next higher configuration
    // (e.g. folder or global) will be used
    def configuration = [vaultUrl: 'http://vault.liando.cn:8200',
                         vaultCredentialId: 'vault-approle',
                         engineVersion: 1]
    // inside this block your credentials will be available as env variables
    withVault([configuration: configuration, vaultSecrets: secrets]) {
        sh 'echo $testing'
        sh 'echo $testing_again'
        sh 'echo $another_test'
    }

when I use approle as the credentials  it shows:

20:16:57  [Pipeline] {
20:16:57  [Pipeline] withVault
20:16:57  Retrieving secret: secrets/kv/hello
20:16:57  Access denied to Vault Secrets at 'secrets/kv/hello'
20:16:57  [Pipeline] {
20:16:57  [Pipeline] sh (hide)

### Reproduction steps

1, configure the creditial in vault plugin with root token and approle in vault

2, use these creditial in the script pipeline

### Expected Results

hello test

### Actual Results

error as above

**Comment by hchakrouun** [comment]
Try to get the secret using API directly in command line (like curl ... ) using a role-id and secret-id of the your role. Pay attention to the version of the secret engine. You need to assign a right policy for your role to have access to path: secrets/kv/hello too.

**Comment by Vincent1984** [comment]
> Try to get the secret using API directly in command line (like curl ... ) using a role-id and secret-id of your role. Pay attention to the version of the secret engine. You need to assign a right policy for your role to have access to the path: secrets/kv/hello too.

I have used curl in my code, with the token, but It is nothing help on the plugin,why the plugin do not work on credential ? I have used before, the root token was worked fine at that time.  

<img width="817" alt="微信图片_20220106215232" src="https://user-images.githubusercontent.com/3183359/148393253-d68fa9b4-3baa-45e0-830b-c847be69c07e.png">

**Comment by Vincent1984** [comment]
> > Try to get the secret using API directly in command line (like curl ... ) using a role-id and secret-id of your role. Pay attention to the version of the secret engine. You need to assign a right policy for your role to have access to the path: secrets/kv/hello too.
> 
> I have used curl in my code, with the token, but It is nothing help on the plugin,why the plugin do not work on credential ? I have used before, the root token was worked fine at that time.
> 
> <img alt="微信图片_20220106215232" width="817" src="https://user-images.githubusercontent.com/3183359/148393253-d68fa9b4-3baa-45e0-830b-c847be69c07e.png">

 // inside this block your credentials will be available as env variables
    withVault([configuration: configuration, vaultSecrets: secrets]) {
        sh 'curl --header "X-Vault-Token: s.CrNPW8bJTtMgsgppHngkrDuY"  http://vault.liando.cn:8200/v1/auth/approle/role/my-role/role-id'
        sh 'echo $testing'
        sh 'echo $testing_again'
        sh 'echo $another_test'
    }

> > Try to get the secret using API directly in command line (like curl ... ) using a role-id and secret-id of your role. Pay attention to the version of the secret engine. You need to assign a right policy for your role to have access to the path: secrets/kv/hello too.
> 
> I have used curl in my code, with the token, but It is nothing help on the plugin,why the plugin do not work on credential ? I have used before, the root token was worked fine at that time.
> 
> <img alt="微信图片_20220106215232" width="817" src="https://user-images.githubusercontent.com/3183359/148393253-d68fa9b4-3baa-45e0-830b-c847be69c07e.png">

> > Try to get the secret using API directly in command line (like curl ... ) using a role-id and secret-id of your role. Pay attention to the version of the secret engine. You need to assign a right policy for your role to have access to the path: secrets/kv/hello too.
> 
> I have used curl in my code, with the token, but It is nothing help on the plugin,why the plugin do not work on credential ? I have used before, the root token was worked fine at that time.
> 
> <img alt="微信图片_20220106215232" width="817" src="https://user-images.githubusercontent.com/3183359/148393253-d68fa9b4-3baa-45e0-830b-c847be69c07e.png">

 // inside this block your credentials will be available as env variables
    withVault([configuration: configuration, vaultSecrets: secrets]) {
        sh 'curl --header "X-Vault-Token: s.CrNPW8bJTtMgsgppHngkrDuY"  http://vault.liando.cn:8200/v1/auth/approle/role/my-role/role-id'
        sh 'echo $testing'
        sh 'echo $testing_again'
        sh 'echo $another_test'
    }

**Comment by hchakrouun** [comment]
Can you give the result this request from your command line (not from the pipeline) ?
`curl -H "X-Vault-Token: s.CrNPW8bJTtMgsgppHngkrDuY" http://vault.liando.cn:8200/v1/auth/approle/role/my-role/role-id `
and if you have access to your Vault installation, give the result of the command too:
```
# login as admin
vault login s.CrNPW8bJTtMgsgppHngkrDuY
# get role-id of **my-role** role
vault kv get auth/approle/role/my-role/role-id

```
Waiting for you reply.

**Comment by Vincent1984** [comment]
> vault read auth/approle/role/my-role/role-id

[root@ma-mgr-jenkins ~]# curl -H "X-Vault-Token: s.CrNPW8bJTtMgsgppHngkrDuY" http://vault.liando.cn:8200/v1/auth/approle/role/my-role/role-id
{"request_id":"dc4e107f-33b4-9485-d9c1-fa1b0c173769","lease_id":"","renewable":false,"lease_duration":0,"data":{"role_id":"01cecfd1-db23-7fd7-b924-28a84c63a22f"},"wrap_info":null,"warnings":null,"auth":null}


Last login: Thu Jan  6 19:29:46 2022 from 10.0.8.20
[root@vmtemplate ~]# export VAULT_TOKEN="s.CrNPW8bJTtMgsgppHngkrDuY"
[root@vmtemplate ~]# vault read auth/approle/role/my-role/role-id
Error reading auth/approle/role/my-role/role-id: Get "https://127.0.0.1:8200/v1/auth/approle/role/my-role/role-id": http: server gave HTTP response to HTTPS client
[root@vmtemplate ~]# export VAULT_ADDR='http://127.0.0.1:8200'
[root@vmtemplate ~]# vault read auth/approle/role/my-role/role-id
Key        Value
---        -----
role_id    01cecfd1-db23-7fd7-b924-28a84c63a22f

**Comment by hchakrouun** [comment]
Now that you have a role-id,
Get the secret-id
`vault write -f auth/approle/role/my-role/secret-id`
Then use the **role-id** and **secret-id** to get your secret:
`curl -H "X-Vault-Token: s.CrNPW8bJTtMgsgppHngkrDuY" http://vault.liando.cn:8200/v1/secrets/kv/hello`
If you don't get it, give us some detail about how did you activate your **secrets engine** mainly the **path** and **version**

**Comment by Vincent1984** [comment]
> Now that you have a role-id, Get the secret-id `vault write -f auth/approle/role/my-role/secret-id` Then use the **role-id** and **secret-id** to get your secret: `curl -H "X-Vault-Token: s.CrNPW8bJTtMgsgppHngkrDuY" http://vault.liando.cn:8200/v1/secrets/kv/hello` If you don't get it, give us some detail about how did you activate your **secrets engine** mainly the **path** and **version**

It works fine with roleid. but for the auth issue, I have to use root token for the request, So how can I use root token? Currently it shows error above

**Comment by hchakrouun** [comment]
Get the role-id and secret-id of the role you want to use (**root** if you want), edit your project pipeline by clicking **configure**, you 'll see an attribute called **Vault plugin** create an approle credential (with your secret-id and role-id) then choose it, don't forget to choose the right engine version in the same form, then save.
you can now go the cerdentials section of your project, and create a credential you want and point it to you secret in vault, once you do that, go to you jenkinsfile and use **credentials("your_crdentials_id_goes_here")** , that's all you need to do
