### ISSUE TITLE
Jobs were not apeearing on console after HashiCorp Vault Plugin Version upgrade to 364.vf5d54b_3dc313

### ISSUE THREAD

**Issue by baban-babs** [jenkinsci/hashicorp-vault-plugin#324]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  2024-01-31 06:59:42.910+0000 [id=35856] WARNING h.ExpressionFactory2$JexlExpression#evaluate: Caught exception evaluating: h.hasPermission(it, permission) in /jenkins/job/jobname/. Reason: java.lang.NullPointerException: Cannot invoke "hudson.model.ViewGroup.getACL()" because the return value of "hudson.model.View.getOwner()" is null
java.lang.NullPointerException: Cannot invoke "hudson.model.ViewGroup.getACL()" because the return value of "hudson.model.View.getOwner()" is null

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Red Hat Linux

### Reproduction steps

1 Upgrade HashiCorp Vault Plugin to Version 364.vf5d54b_3dc313
2 Restart the Jenkins Controller
3 Once you click on  job folder, you will encounter some error on console and job will be not visible

### Expected Results

Job should be visible 

### Actual Results

Job not visible on Jenkins Controller GUI. Reporting error .

**Comment by brian-leveille** [comment]
I have this issue also.

**Comment by baban-babs** [comment]
> I have this issue also.

Yeah i have rolled back to old plugin version.  I think we need to wait for new version

**Comment by bordenit** [comment]
Same issue here. I believe it is related to this closed issue as well, as I saw that error initially and then removed the tokenExpiry to see this new error.  #323

**Comment by clintonsteiner** [comment]
Same issue - downleveling fixed the issue for me

**Comment by bordenit** [comment]
@clintonsteiner did you try going to latest version from 360.v0a_1c04cf807d? That's my next attempt before redoing the folders. Hoping going from 360.v0a_1c04cf807d to latest will just work.

**Comment by clintonsteiner** [comment]
@bordenit issue for me still existed with latest

**Comment by clintonsteiner** [comment]
Bumping this issue - this is a major regression introduced and we should rollback the available plugin until a fix is introduced

**Comment by clintonsteiner** [comment]
Think we should close this issue in favor of https://github.com/jenkinsci/hashicorp-vault-plugin/issues/326

**Comment by baban-babs** [comment]
Yeah this issue has been  fixed now in latest vault plugin
