### ISSUE TITLE
Creating VaultAppRoleCredential with jenkins-dsl

### ISSUE THREAD

**Issue by jsknnr** [jenkinsci/hashicorp-vault-plugin#77]
I am trying to create a VaultAppRoleCredential and attach it to the properties of a folder during creation via jenkins-dsl. The folder, the FolderCredentialProperty and the DomainCredential all are being created just fine. When I get to actually creating the VaultAppRoleCredential to attach it I end up getting a method signature exception on type `Secret secretId`.

I am correctly importing `hudson.util.Secret` and using the fromString method to create a secret to assign to `secretId`, however, I am still getting: `No signature of method: javaposse.jobdsl.plugin.structs.DescribableContext.secretId() is applicable for argument types: (hudson.util.Secret)`

The job-dsl describable context helper is correctly finding VaultAppRoleCredential and correctly returning the constructor as: `public com.datapipe.jenkins.vault.credentials.VaultAppRoleCredential(com.cloudbees.plugins.credentials.CredentialsScope,java.lang.String,java.lang.String,java.lang.String,hudson.util.Secret,java.lang.String)`

This has been super confusing to me as I am handing it exactly what it expects. After logs of debugging I think I may have found the issue. Further through the context building when job-dsl tries to, I guess for a lack of a better word, resolve, the constructor types it ends up displaying this: `VaultAppRoleCredential(scope: CredentialsScope[SYSTEM, GLOBAL, USER], id: String, description: String, roleId: String, secretId: org.kohsuke.stapler.NoStaplerConstructorException: There's no @DataBoundConstructor on any constructor of class hudson.util.Secret, path: String)`

At this point it appears to set the value type of secretId to an ErrorType instead of a hudson.util.Secret type, resulting in the method signature error I ultimately end up receiving.

Is there any insight on how to resolve this issue with the DataBoundConstructor?

Version information:
Jenkins: 2.190.2
Folders Plugin: 6.10.1
Credentials Plugin: 2.3.0
Hashicorp Vault Plugin : 3.0.0
Jenkins Job-DSL Plugin: 1.76

**Comment by jfroche** [comment]
We face this problem as well. Did you try your code with this pull request: https://github.com/jenkinsci/job-dsl-plugin/pull/1202 ?

**Comment by casz** [comment]
I guess your actually affected by https://github.com/jenkinsci/jenkins/pull/4516

**Comment by hypePG** [comment]
any news on this? is it possible to create approle credentials with dsl?

**Comment by jetersen** [comment]
Blocked by https://github.com/jenkinsci/job-dsl-plugin/pull/1202

**Comment by jamietanna** [comment]
This is now unblocked :smile:

**Comment by jetersen** [comment]
Closing issue
