### ISSUE TITLE
Secrets not masked in build logs

### ISSUE THREAD

**Issue by corradomatt** [jenkinsci/hashicorp-vault-plugin#78]
Using version 3.1.1 of this plugin on Jenkins version 2.204.2 I'm seeing that the secrets loaded from our vault instance are not being masked as other credential providers do and I'm lead to believe by the first paragraph of the README.md.

Here's my sample config for loading the secrets:

```groovy
def secrets = [
    [$class: 'VaultSecret', path: 'secret/my/path-1', secretValues: [
        [$class: 'VaultSecretValue', envVar: 'testing', vaultKey: 'value']]],
    [$class: 'VaultSecret', path: 'secret/my/path-2', secretValues: [
        [$class: 'VaultSecretValue', envVar: 'another_test', vaultKey: 'yaml']]]
]

# Try using wrap
wrap([$class: 'VaultBuildWrapper', vaultSecrets: secrets]) {
    sh 'echo $testing'
    sh 'echo $another_test'
}

# Try using withVault
withVault([vaultSecrets: secrets]) {
    sh 'echo $testing'
    sh 'echo $another_test'
} 
```

In both cases I get the full secret output to the console when I would expect to see only `****`.

Is this a known issue? Or I am doing it wrong?

**Comment by corradomatt** [comment]
After further testing I see that secrets comprised of single lines of text are masked.

I assume that since my first test consisted of larger text blobs spanning multiple lines Jenkins doesn't mask it?

**Comment by marshallford** [comment]
I'm running into the same issue with multi line secrets. I'm unclear if this is a limitation of the plugin or a Jenkins bug?

**Comment by tomlankhorst** [comment]
Same issue here, single-lined secrets are masked, multi-lined not. Plugin 3.2.0.

**Comment by jetersen** [comment]
This is a common issue when dealing with logs and multiline secrets.
There is no good way of hiding multiline secrets as they could potentially end up matching some part of the log you do not want masked.

We could properly apply a similar pr: https://github.com/jenkinsci/credentials-binding-plugin/pull/92

**Comment by tomlankhorst** [comment]
@jetersen First of all, thank you for all your effort! I really appreciate it. 

> There is no good way of hiding multiline secrets as they could potentially end up masking some part of the log you do not want masked.

That is understandable. However, multi-line secrets are a common and perfectly fine use-case. 
Though there is currently no suitable solution to this issue, the issue itself still stands, right? 

Maybe, for the sake of discussion, we can keep this issue open to facilitate working towards a solution.

**Comment by jetersen** [comment]
Well both gitlab and Jenkins has yet to solve the problem

**Comment by agaudreault-jive** [comment]
Referencing this  for tracking purpose.
https://issues.jenkins-ci.org/browse/SECURITY-1874

**Comment by jetersen** [comment]
@agaudreault-jive not likely to get any traction since it's hard to decorate a multiple line string in any log system.
