### ISSUE TITLE
Skip SSL verification does not work even if it's checked from plugin configuration

### ISSUE THREAD

**Issue by suhasln** [jenkinsci/hashicorp-vault-plugin#79]
Also I found a workaround; adding  skipSslVerification property to pipeline configuration makes it work.

 def secrets = [
        [path: 'secret/windows', engineVersion: 1, secretValues: [
            [envVar: 'pass', vaultKey: 'password']]],
        [path: 'kvtest/user', engineVersion: 1, secretValues: [
            [vaultKey: 'name']]]
    ]
    
    def configuration = [vaultUrl: 'https://vault.company.com',
                         skipSslVerification: 'true',
                         vaultCredentialId: 'Vault',
                         engineVersion: 1]

    withVault([configuration: configuration, vaultSecrets: secrets]) {
        sh 'echo $pass'
        sh 'echo $name'
    }

**Comment by jgracin** [comment]
Hi! I can confirm this. Thanks!

**Comment by jetersen** [comment]
There might be a issue in the configuration resolver.

**Comment by jetersen** [comment]
Hmm this is a problem with merging with the parent.

Looking into a fix 😓
