### ISSUE TITLE
com.datapipe.jenkins.vault.credentials.common.Vault Username Password Credential Impl getVaultSecret WARNING: Cannot retrieve secret becuase Jenkins.instance is not available

### ISSUE THREAD

**Issue by DegalaS** [jenkinsci/hashicorp-vault-plugin#80]
I want to do multi branch checkout using hashicorp vault secrets.

I have created credentials in Jenkins credentials store using the option vault username and password. Using that credentials id my checkout working fine in master nodes. But when my job running in slave it fails with below log.

 

com.datapipe.jenkins.vault.credentials.common.Vault Username Password Credential Impl getVaultSecret
WARNING: Cannot retrieve secret becuase Jenkins.instance is not available

I assume Jenkins.instance value only available in master node. As this value not available in slave nodes jobs are not able fetch the credentials. This bug have to be fixed.

Or else provide solutions to achieve my requirements.

**Comment by jetersen** [comment]
Newer version secrets are always retrieved on master even when agents needs them.
