### ISSUE TITLE
java.lang.NullPointerException at com.datapipe.jenkins.vault.VaultBuildWrapper.provideEnvironmentVariablesFromVault(VaultBuildWrapper.java:139)

### ISSUE THREAD

**Issue by ecliptik** [jenkinsci/hashicorp-vault-plugin#81]
Earlier this week we updated our Jenkins server to 2.204.2 and the Hashicorp Vault Plugin from 2.5.0 to 3.1.1. Now triggered jobs (github push/PR, timer, triggered from other jobs) using the Vault Plugin are giving the following error,

```
FATAL: nulljava.lang.NullPointerException
at com.datapipe.jenkins.vault.VaultBuildWrapper.provideEnvironmentVariablesFromVault(VaultBuildWrapper.java:139)
at com.datapipe.jenkins.vault.VaultBuildWrapper.setUp(VaultBuildWrapper.java:94)
at jenkins.tasks.SimpleBuildWrapper.setUp(SimpleBuildWrapper.java:146)
at hudson.model.Build$BuildExecution.doRun(Build.java:157)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
at hudson.model.Run.execute(Run.java:1853)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:97)
at hudson.model.Executor.run(Executor.java:427) 
```

We've rolledback the plugin to 2.5.0 but it still occurs. Verified the Global jenkins-plugin is set to KV Engine Version 1, and all the jobs are set to 1 as well. Vault server version is 1.0.2 and KV 2 is not enabled.

Running or re-building a job manually will not have this error. I added [a comment to previous issue](https://issues.jenkins-ci.org/browse/JENKINS-58991?focusedCommentId=385605&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-385605) in the Jenkins Jira on a related bug as well.

Other information:
- Jenkins Master OS: Ubuntu 18.04.4
- Jenkins Version: 2.204.2
- Vault Plugin Version: 2.5.0 and 3.1.1
- Java version: OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
- Vault Server version: 1.0.2
- Jenkins jobs all run on remote jenkins agents using swarm plugin version 3.18 and Java 1.8.0-8u242 on Ubuntu 18.04.4

**Comment by ecliptik** [comment]
Small update on this, it appears the NPE no longer occurs when Jenkins is configured this way:

1. Jenkins Advanced Configuration has K/V Engine Version set to Version 1 (since our Vault server is KV v1 only)
2. Job vault-plugin configuration K/V Engine Version is set to Default
3. Job vault-plugin Advanced Configuration K/V Engine Version is set to Default

Not quite sure why it would make a difference with K/V Engine Version set to 1 as well to match the Global configuration. However when jobs are not using Default they fail with a NPE.

**Comment by casz** [comment]
Hmm you stacktrace and lines do not match up with the release of 3.1.1 🤔

**Comment by ecliptik** [comment]
We were getting this with 3.1.1 and 2.5.0, I may have copied the stacktrace from when it was running 2.5.0. I updated the plugin back to 3.1.1 since both versions were giving a NPE.

Here's a stacktrace from a job this morning after the 3.1.1, but before I changed the vault-plugin configuration in the job from 1->Default,

```
FATAL: null
java.lang.NullPointerException
	at com.datapipe.jenkins.vault.VaultBuildWrapper.provideEnvironmentVariablesFromVault(VaultBuildWrapper.java:142)
	at com.datapipe.jenkins.vault.VaultBuildWrapper.setUp(VaultBuildWrapper.java:95)
	at jenkins.tasks.SimpleBuildWrapper.setUp(SimpleBuildWrapper.java:146)
	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1853)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
```

Once I changed the K/V engine version to default it no longer had a NPE.

**Comment by casz** [comment]
🤔 Java being java...

For some reason: `vaultAccessor` is null

**Comment by casz** [comment]
@ecliptik mind testing https://ci.jenkins.io/job/Plugins/job/hashicorp-vault-plugin/job/PR-82/1/artifact/com/datapipe/jenkins/plugins/hashicorp-vault-plugin/3.1.2-rc280.05b7179ebc99/hashicorp-vault-plugin-3.1.2-rc280.05b7179ebc99.hpi ? :)

**Comment by ecliptik** [comment]
@casz I've applied the 3.1.2-rc hpi and vault-plugin is now reporting version `3.1.2-rc280.05b7179ebc99`.

I'll watch jobs and solicit feedback from devs who have been running into this occasionally to see if it improves things and will let you know. Thank you for the quick response and fix.

**Comment by tony-snyder-fc** [comment]
I pulled this fix into our jenkins as well. So far so good.  We load all our jobs in via Jenkins DSL. and even if we set the engineVersion() in the config block and the secret blocks, it still wouldn't work properly unless we manually saved the job after loading the dsl.   This hpi version works as expected. Thank you for jumping on it!

**Comment by casz** [comment]
I'll get a release shipped than 👌

**Comment by ecliptik** [comment]
Just to follow-up, we've been running the 3.1.2-rc280 hpi for the last week and everything is smooth. Thank you @casz for fixing this up and getting it released.
