### ISSUE TITLE
Vault credentials not found for  <path>

### ISSUE THREAD

**Issue by Asgoret** [jenkinsci/hashicorp-vault-plugin#83]
Can somebody help me plz? @casz

=======
Versions:
```
- Jenkins: 2.217
- Plugin: 3.1.1
- Vault: 1.3.2
```
=======
Code:
```
    def secrets = [
    [path: 'secret/data/jenkins', secretValues: [
        [vaultKey: 'ad_pass']]]
    ]

    def vaultConfiguration = [vaultUrl: 'https://vault.some.nda.domain/',
            vaultCredentialId: 'admin-vault-token', skipSslVerification: true, engineVersion: 2]
    withVault([configuration: vaultConfiguration, vaultSecrets: secrets]){
        docker.withRegistry('https://some.docker.registry','ad_pass') {
            sh 'echo $ad_pass'
            // sh """
            //     make build-cloud
            // """
        }
    }
```
=======
In vault I tried different level disposition of creds (like `secret/jenkins/ad_pass` or `jenkins/ad_pass`). But in all cases I have this error:
```
com.datapipe.jenkins.vault.exception.VaultPluginException: Vault credentials not found for 'secret/data/jenkins'
	at com.datapipe.jenkins.vault.VaultBuildWrapper.responseHasErrors(VaultBuildWrapper.java:192)
	at com.datapipe.jenkins.vault.VaultBuildWrapper.provideEnvironmentVariablesFromVault(VaultBuildWrapper.java:154)
	at com.datapipe.jenkins.vault.VaultBuildWrapper.setUp(VaultBuildWrapper.java:95)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2.doStart(CoreWrapperStep.java:97)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Asgoret** [comment]
Ok...I found the problem.
Correct secret:
```
    def secrets = [
    [path: 'secret/jenkins/ad_pass', secretValues: [
            [vaultKey: 'username'],
            [vaultKey: 'password']
            ]
        ]
    ]
```

And now I wonder how I can set this secret as a credential for using with other plugins.... for example, `docker.withRegistry` [Documentation](https://jenkins.io/doc/pipeline/steps/docker-workflow/#withdockerregistry-sets-up-docker-registry-endpoint)

**Comment by casz** [comment]
if you do not specify a envKey it will se the vaultKey so `env.username`` or `sh "echo $username"`

**Comment by Asgoret** [comment]
@casz but I don't need separate `username` or `password` I need `ad_pass` credential for using other plugins.

**Comment by casz** [comment]
just save them together in the value you want to take out

vaultKey is whatever field you have in the key field.

**Comment by casz** [comment]
again it is just groovy so you can also do `"{env.username}{env.password}"`

**Comment by Asgoret** [comment]
@casz Your way helped me add creds to job, but I still can't use them with docker plugin for registry login. 
Is there any examples or documentation about this class `VaultUsernamePasswordCredentialBinding`? I found it here [link](https://jenkins.io/doc/pipeline/steps/credentials-binding/)

**Comment by casz** [comment]
@Asgoret I suggest looking at configuration as code which supports resolving vault secrets and can be applied to global plugin configuration.

**Comment by Asgoret** [comment]
@Jetersen Hi! I configured vault as casc, but I still can't use secrets stored in vault as variables for other plugins.
Logs from system logger:
```
Mar 11, 2020 10:59:25 AM FINE com.datapipe.jenkins.vault.jcasc.secrets.VaultSecretSource
Attempting to connect to Vault: Optional[https://very secret adress/]
Mar 11, 2020 10:59:25 AM FINE com.datapipe.jenkins.vault.jcasc.secrets.VaultSecretSource
Using engine version: 2
```
 Vault casc:
```
CASC_VAULT_TOKEN=<value>
CASC_VAULT_PATHS=secret/data/jenkins/ad_pass
CASC_VAULT_URL=https://very secret adress/
CASC_VAULT_ENGINE_VERSION=2
```

**Comment by Jetersen** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/credentials
