### ISSUE TITLE
prefixPath : Generalization to other usages and Secret Parameter configuration

### ISSUE THREAD

**Issue by lenaing** [jenkinsci/hashicorp-vault-plugin#84]
Hello,

Thanks to https://github.com/jenkinsci/hashicorp-vault-plugin/pull/67  we can (finally !) request secrets from non-at-root mounted KVs. And that's great ! 👍 

Now we can do this in a scripted pipeline :
```groovy
def secrets = [
    [path: 'test/nonrootkv/secret', secretValues: [[envVar: 'result', vaultKey: 'secretkey']]]
]

def configuration = [
    vaultUrl: 'https://vault.example.com',
    prefixPath: 'test/nonrootkv/',
    vaultCredentialId: 'credentialID'
]

pipeline {
    agent {
        node {
            label 'default'
        }
    }
    stages {
        stage('Test get Secret'){
            steps {
                script {
                    withVault([configuration: configuration, vaultSecrets: secrets]) {
                        sh 'if [ -n "${result}" ]; then echo "variable is defined" && echo "test${result}"; else exit 1 ; fi'
                    }
                }
            }
        }
    }
}
```
However :
* This isn't documented in the `README.md`
* It would be nice to enable the `prefixPath` parameterization at many levels. On the top of my head I think about non-at-root mounted authentication endpoints. This would enable tidying of users' Vault mount points rather than requiring them to have everything mounted at the Vault root.
* The Vault Secret UI config parameter does not enable a user to set a `prefixPath` for a non-root KV (and fails to read such secrets) :
![vault_secret](https://user-images.githubusercontent.com/1098971/76086521-85b1de80-5fb4-11ea-96b4-9eaac57de782.png)

Kind regards

**Comment by Jetersen** [comment]
Feel free to submit a PR your halfway there anyhow.
