### ISSUE TITLE
Secret with empty values garbles logs

### ISSUE THREAD

**Issue by maorfr** [jenkinsci/hashicorp-vault-plugin#87]
Hello,

We are using this plugin extensively, so first of all thank you for the great work!

We have noticed that when a referenced Vault secret key contains an empty value, the entire log is filled with `****`.

For example, the `SUCCESS` message will be shown as `****S****U****C****C****E****S****`.

We believe that the empty value is the reason and the culprit is probably around:
https://github.com/jenkinsci/hashicorp-vault-plugin/blob/master/src/main/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilter.java#L47

This has an easy workaround, which is to not have empty values in secrets.
This can also be checked and handled.

Let me know if that makes sense and if we should attempt to fix this in a PR.

Note: We are using version 2.1/2.2 of the plugin.

Thanks again!

**Comment by jetersen** [comment]
Yup, this is the very same reason why #78 will never work.

I think however this could be solved mostly by implementing a credential provider so we can rely on the credential plugins masking of credentials.
