### ISSUE TITLE
Build continues when access is denied

### ISSUE THREAD

**Issue by jantman** [jenkinsci/hashicorp-vault-plugin#90]
Using version 3.1.1 of the plugin and a ``withVault`` block in a Jenkinsfile pipeline, the build just continues on if access is denied:

```
...
[Pipeline] withVault
10:14:19 Access denied to Vault Secrets at 'secret/<path>'
[Pipeline] {
[Pipeline] properties
[Pipeline] stage
...
```

I find it extremely difficult to think of a case where ignoring this (fatal) error is what users would expect, or a case where not having expected secrets present will allow a build to continue as expected. We had multiple builds produce broken results until we found this line in the output.

Would it be possible to either fix this so that access denied errors result in a build failure, or add a *global* configuration option to make that happen? We have hundreds of pipelines using this plugin (once again, thanks so much for this!!!) and would really like to make sure they all act as we'd expected.

**Comment by jetersen** [comment]
Does the `Fail if path is not found` option not work for you?

**Comment by jantman** [comment]
> We have hundreds of pipelines using this plugin (once again, thanks so much for this!!!) and would really like to make sure they all act as we'd expected.

The `Fail if path is not found` option would probably work for us, but the problem is that it defaults to false and there's no way to change this. We'd need to update literally hundreds of Jenkinsfile, JobDSL, and manually-created jobs/pipelines, and we'd need to teach everyone who creates jobs/pipelines to remember to set this option every time they retrieve a secret.

The crux of this feature request is: "We expect (principal of least surprise) a build to fail if retrieving a secret fails, and would like this to either be the default behavior, or would like a global option to make this the default behavior."

We don't want developers to have to remember to add another option to the Vault calls in order to enable non-surprising behavior.

**Comment by jetersen** [comment]
You should be able to apply it globally_

**Comment by jetersen** [comment]
if not than the config merger is doing it wrong 😓

**Comment by jantman** [comment]
Aha! Apologies, I didn't realize it was hidden in the "Advanced" section. It looks like this should fit our use case perfectly, thanks!
