### ISSUE TITLE
var/run/secrets/kubernetes.io/serviceaccount/token: No such file or directory 

### ISSUE THREAD

**Issue by sarabesh** [jenkinsci/hashicorp-vault-plugin#98]
I have Jenkins set up in such a way that master runs in local and its slaves are run as pods in k8s. Vault is also running in the same k8 setup. When I try using the Kubernetes auth method in Jenkins plugin, it returns "var/run/secrets/kubernetes.io/serviceaccount/token: No such file or directory ". I printed the token using sh "cat var/run/secrets/kubernetes.io/serviceaccount/token", in Jenkins build itself to make sure the file is present. I was able to see the printed jwt token, but i am not sure why the plugin could'nt get the token.

**Comment by cpoole** [comment]
all plugins (and Jenkinsfile groovy scripts) run on the master. The service account token the plugin is looking for must be on the master filesystem.

**Comment by sarabesh** [comment]
Thanks for the response @cpoole .so does it still check-in Jenkins master even if I use the withVault() within node in podTemplate?

**Comment by cpoole** [comment]
Yes, it's all performed on the master

**Comment by jetersen** [comment]
This is most likely a won't fix as it would be both a security issue and agents can have wildly different configurations.
